API_ID = "YOUR_ID"
API_HASH = "YOUR_HASH"
CHANNEL_USERNAME = "@YOUR_CHANNEL_TAG"
TARGET_CHANNEL_USERNAME = '@YOUR_CHANNEL_TAG_TO_POST'
DOWNLOAD_DIR1 = 'YOUR_DIR1'
DOWNLOAD_DIR2 = 'YOUR_DIR2'
BOT_TOKEN = 'YOUR_BOT_TOKEN'